Colegio/Innova/Models/Curricula.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Innova.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curricula
    {
        public Curricula()
        {
            this.DetalleCurricula = new HashSet<DetalleCurricula>();
        }
    
        public int IdCurricula { get; set; }
        public Nullable<int> IdNivel { get; set; }
        public Nullable<int> IdCurriculaBase { get; set; }
        public Nullable<int> Estado { get; set; }
    
        public virtual CurriculaBase CurriculaBase { get; set; }
        public virtual Nivel Nivel { get; set; }
        public virtual ICollection<DetalleCurricula> DetalleCurricula { get; set; }
    }
}

Colegio/Innova/Controllers/CurriculaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Runtime.Serialization.Json;
using System.Web.Script.Serialization;
using Innova.Models;


namespace Innova.Controllers
{
    public class CurriculaController : Controller
    {
        //
        // GET: /Curricula/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Base()
        {
            return PartialView();
        }

        public ActionResult ListaBase(FormCollection form)
        {
            //string inicio = "", string fin = "", string resolucion = ""
            var inicio = form["txtDesde"];
            var fin = form["txtHasta"];
            var resolucion = form["txtResolucion"];

            if (inicio == null && fin == null && resolucion == null)
            {
                ViewBag.Lista = GestionPedagogica.ListarBase();
                return PartialView();
            }
            else if (inicio == "" && fin == "" && resolucion == "")
            {
                ViewBag.Lista = GestionPedagogica.ListarBase();
                return PartialView();
            }
            else
            {
                ViewBag.Lista = GestionPedagogica.BuscarListaBase(inicio, fin, resolucion);
                return PartialView();
            }
        }

        public ActionResult BuscarBase()
        {
            return PartialView();
        }
        public ActionResult FormBase(int idCurriculaBase = 0)
        {

            ViewBag.Base = GestionPedagogica.ObtenerBase(idCurriculaBase);
            ViewBag.IdCurriculaBase = idCurriculaBase;

            return PartialView();
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult RegistrarBase(FormCollection form)
        {
            var idCurriculaBase = Convert.ToInt32(form["hidIdCurriculaBase"]);
            var anno = Convert.ToInt32(form["txtAnno"]);
            var resolucion = form["txtResolucion"];
            var descripcion = form["txtDescripcion"];
            var vigencia = false;
            if (form["chkVigencia"] != null)
            {
                vigencia = form["chkVigencia"].IndexOf("true", System.StringComparison.Ordinal) != -1;
            }

            var setBase = new CurriculaBase()
            {
                IdCurriculaBase = idCurriculaBase,
                Año = anno,
                NumeroResolucion = resolucion,
                Descripcion = descripcion,
                Vigencia = vigencia
            };

            var exito = GestionPedagogica.RegistrarCurriculaBase(setBase);

            var js = new JavaScriptSerializer();
            return Content(js.Serialize(exito));
        }

        public ActionResult FormCompetenciaCapacidadArea(int idCurriculaBase = 0)
        {

            ViewBag.listaArea = new SelectList(GestionPedagogica.ListarAreaCurricular(), "IdAreaCurricular", "Nombre");
            ViewBag.listaCompetencia = new SelectList(GestionPedagogica.ListarCompetencia(), "IdCompetencia", "Nombre");
            ViewBag.IdCurriculaBase = idCurriculaBase;
            return PartialView();
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult RegistrarCompetenciaxArea(FormCollection form)
        {
            var idCurriculaBase = Convert.ToInt32(form["hidIdCurriculaBase"]);
            var area = Convert.ToInt32(form["cboArea"]);
            var competencia = Convert.ToInt32(form["cboCompetencia"]);

            var setBaseCompetencia = new CurriculaBaseCompetencia()
            {
                IdCurriculaBase = idCurriculaBase,
                IdAreaCurricular = area,
                IdCompetencia = competencia
            };

            var exito = GestionPedagogica.RegistrarCompetenciaArea(setBaseCompetencia);

            var js = new JavaScriptSerializer();
            return Content(js.Serialize(exito));
        }


        public ActionResult ElininarCompetenciaxArea(int idCurriculaBaseCompetencia)
        {

            var exito = GestionPedagogica.EliminarCompetenciaCapadidadArea(idCurriculaBaseCompetencia);
            var js = new JavaScriptSerializer();
            return Content(js.Serialize(exito));
        }


        public ActionResult ListaAreaCompetencia(int idCurriculaBase = 0)
        {

            ViewBag.Lista = GestionPedagogica.ListarCompetenciaCapadidadArea(idCurriculaBase);

            return PartialView();
        }
    }
}

Colegio/Innova/Views/Curricula/Base.cshtml
<div id="idBusquedaBase">
    @{Html.RenderAction("BuscarBase", "Curricula");}
</div>

<br />
<br />

<div id="resultadoBusquedaBase">
    @{Html.RenderAction("ListaBase", "Curricula");}
</div>

Colegio/Innova/Views/Curricula/BuscarBase.cshtml
@{
    <div class="form-inline">

        <div class="form-group">

            @using (Html.BeginForm("ListaBase", "Curricula", FormMethod.Post, new { id = "formBusquedaBase", @class = "form-inline" }))
            {

                <h4 class="form-signin-heading">Consulta de Currículas Base</h4>
                <div class="form-group">
                    @Html.Label("lblDesde", "Desde")<br />
                    @Html.TextBox("txtDesde", null, new { @class = "form-control solo-numero", maxlength = "4" })
                </div>

                <div class="form-group">
                    @Html.Label("lblHasta", "Hasta")<br />
                    @Html.TextBox("txtHasta", null, new { @class = "form-control solo-numero", maxlength = "4" })
                </div>

                <div class="form-group">
                    @Html.Label("lblResolucion", "Resolución Ministerial")<br />
                    @Html.TextBox("txtResolucion", null, new { @class = "form-control", maxlength = "20" })
                </div>

                <div class="form-group">
                    <br />
                    <button class="btn btn-primary" type="submit" id="btnBusquedaBase">
                        Buscar
                    </button>
                </div>

            }
        </div>

        <div class="form-group">
            <div class="form-group">
                <br /><br /><br />
                <button class="btn btn-primary" type="submit" id="btnLimpiarBusquedaBase" >
                    Limpiar
                </button>
            </div>
        </div>

    </div>




}


<script type="text/javascript">

    $(document).ready(function () {
        
        $(".solo-numero").keyup(function () {
            this.value = (this.value + '').replace(/[^0-9]/g, '');
        });
    });

    $("#formBusquedaBase").ajaxForm(function (data) {
        $("#resultadoBusquedaBase").html(data);
        $("#resultadoBusquedaBase").slideDown("slow");
    });

    $("#btnLimpiarBusquedaBase").click(function (data) {
        $("#txtDesde").val("");
        $("#txtHasta").val("");
        $("#txtResolucion").val("");
    });

</script>

Colegio/Innova/Views/Curricula/FormBase.cshtml
<script src="@Url.Content("~/Scripts/jquery.form.js")"></script>

@{
    var idCurriculaBase = ViewBag.IdCurriculaBase is int ? (int)ViewBag.IdCurriculaBase : 0;
    var Base = ViewBag.Base as Innova.Models.CurriculaBase;
}
@{ using (Html.BeginForm("RegistrarBase", "Curricula", FormMethod.Post, new { enctype = "multipart/form-data", id = "formRegistrarBase", @class = "form-group", required = "required", }))
 {

     if (Base != null)
     {
        @Html.Hidden("hidIdCurriculaBase", idCurriculaBase)
        <div class="form-group">
            @Html.Label("lblAnno", "Año")
            @Html.TextBox("txtAnno", Base.Año, new { @class = "form-control", maxlength = "100" })
        </div>

        <div class="form-group">
            @Html.Label("lblResolucion", "Resolución Ministerial")
            @Html.TextBox("txtResolucion", Base.NumeroResolucion, new { @class = "form-control", maxlength = "100" })
        </div>

        <div class="form-group">
            @Html.Label("lblDescripcion", "Descripción")
            @Html.TextArea("txtDescripcion", Base.Descripcion, new { @class = "form-control", maxlength = "100" })
        </div>

        <div class="form-group">
            @Html.Label("lblVigencia", "Vigencia")
            @Html.CheckBox("chkVigencia", Base.Vigencia.Value)
        </div>
     }
     else
     {
        @Html.Hidden("hidIdCurriculaBase", idCurriculaBase)
        <div class="form-group">
            @Html.Label("lblAnno", "Año")
            @Html.TextBox("txtAnno", null, new { @class = "form-control solo-numero", maxlength = "4" })
        </div>

        <div class="form-group">
            @Html.Label("lblResolucion", "Resolución Ministerial")
            @Html.TextBox("txtResolucion", null, new { @class = "form-control", maxlength = "20" })
        </div>

        <div class="form-group">
            @Html.Label("lblDescripcion", "Descripción")
            @Html.TextArea("txtDescripcion", null, new { @class = "form-control", maxlength = "1000" })
        </div>

        <div class="form-group">
            @Html.Label("lblVigencia", "Vigencia")
            @Html.CheckBox("chkVigencia", true)
        </div>
     }




    <button class="btn btn-primary" type="submit" id="btnBusquedaBase">
        Registrar
    </button>

 }}

<script type="text/javascript">

    $(document).ready(function () {

        $(".solo-numero").keyup(function () {
            this.value = (this.value + '').replace(/[^0-9]/g, '');
        });
    });


    $("#formRegistrarBase").ajaxForm(function (result) {
        var obj = jQuery.parseJSON(result);
       

        if (obj) {
            alert("Registro satisfactorio");
            $('#BasePopup').modal('hide');
            $('body').removeClass('modal-open');
            $('.modal-backdrop').remove();

            $.post('@Url.Action("ListaBase", "Curricula")', function (data) {
                if (data != null) {
                    $("#resultadoBusquedaBase").html(data);
                    //$("#aTesis2").hide();
                    $("#resultadoBusquedaBase").slideDown("slow");
                }
            });
        } else {
            alert("Lo sentimos hubo un inconveniente en el registro de la curricula base");
        }
    });

</script>

Colegio/Innova/Views/Curricula/FormCompetenciaCapacidadArea.cshtml
<script src="@Url.Content("~/Scripts/jquery.form.js")"></script>

@{

    var idCurriculaBase = ViewBag.IdCurriculaBase is int ? (int)ViewBag.IdCurriculaBase : 0;
    var listaArea = ViewBag.listaArea as SelectList;
    var listaCompetencia = ViewBag.listaCompetencia as SelectList;

}

@{ using (Html.BeginForm("RegistrarCompetenciaxArea", "Curricula", FormMethod.Post, new { enctype = "multipart/form-data", id = "formRegistrarCompetenciaArea", @class = "form-inline", required = "required", }))
 {

    @Html.Hidden("hidIdCurriculaBase", idCurriculaBase)

    <div class="form-group">
        @Html.Label("lbArea", "Área")<br />
        @Html.DropDownList("cboArea", listaArea, "[Seleccionar]", new { required = "required" })
    </div>

    <div class="form-group">
        @Html.Label("lblCompetencia", "Competencia")<br />
        @Html.DropDownList("cboCompetencia", listaCompetencia, "[Seleccionar]", new { required = "required" })
    </div>

    <div class="form-group">
        <br />
        <button class="btn btn-primary" type="submit" id="btnRegistrarCompetenciaArea">
            Agregar
        </button>
    </div>

 }}


<div id="divListaCompetenciaCapacidadArea">

    @{Html.RenderAction("ListaAreaCompetencia", "Curricula", new { idCurriculaBase = @idCurriculaBase});}
    
</div>
<script type="text/javascript">

    $("#formRegistrarCompetenciaArea").ajaxForm(function (result) {
        var obj = jQuery.parseJSON(result);
        var id = $("#hidIdCurriculaBase").val();

        if (obj) {
            alert("Registro satisfactorio");

            $.post('@Url.Action("ListaAreaCompetencia", "Curricula")', { idCurriculaBase: id }, function (data) {
                if (data != null) {
                    $("#divListaCompetenciaCapacidadArea").html(data);
                    $("#divListaCompetenciaCapacidadArea").slideDown("slow");
                }
            });
        } else {
            alert("Lo sentimos hubo un inconveniente en el registro de competencias y capacidades por área curricular");
        }
    });

</script>

Colegio/Innova/Views/Curricula/Index.cshtml
<div class="container">
    <div class="row" style="background-color:gray">
        <div>
            <h3>Inicio</h3>
            <!-- tabs left -->
            <div class="tabbable">
                <ul class="nav nav-pills nav-stacked col-xs-2">
                    <li class="active"><a href="#a" data-toggle="tab">Gestión Pedagógica</a></li>
                    <li ><a href="#b" data-toggle="tab">Gestión de apoyo académico</a></li>
                    <li><a href="#c" data-toggle="tab">Gestión Directiva</a></li>
                    <li><a href="#d" data-toggle="tab">Selección de Personal</a></li>
                    <li><a href="#e" data-toggle="tab">Gestión académica y formativa</a></li>
                    <li><a href="#f" data-toggle="tab">Gestión de gobierno escolar</a></li>


                </ul>
                <div class="tab-content col-xs-10" style="background-color:white">
                    <div class="tab-pane active" id="a">

                        @{Html.RenderAction("Base", "Curricula");
                        }
                    </div>
                    <div class="tab-pane" id="b">Secondo sed ac orci quis tortor imperdiet venenatis. Duis elementum auctor accumsan. Aliquam in felis sit amet augue.</div>
                    <div class="tab-pane" id="c">
                        Thirdamuno, ipsum dolor sit amet, consectetur adipiscing elit. Duis elementum auctor accumsan. Duis pharetra
                        varius quam sit amet vulputate. Quisque mauris augue, molestie tincidunt condimentum vitae.
                    </div>
                    <div id="d"></div>
                    <div id="e"></div>
                    <div id="f"></div>

                </div>
            </div>
            <!-- /tabs -->
        </div>

    </div>
    <!-- /row -->
</div>
<hr>

Colegio/Innova/Views/Curricula/ListaAreaCompetencia.cshtml
@{

    var lista = ViewBag.Lista as List<Innova.Models.GestionPedagogica.ListaCompetenciaCapadidadArea>;
}


<table id="myTableAsesor" class="table table-bordered">

    <thead>
        <tr>
            <th>Area curricular</th>
            <th>Competencia</th>
            <th>Capacidades</th>
            <th></th>
        </tr>
    </thead>

    <tbody>


        @{
            System.Diagnostics.Debug.Assert(lista != null, "lista != null");
        }
        @foreach (var item in lista)
        {
            <tr class="filaCompetenciaxArea" pidcurriculabasecompetencia="@(item.idCurriculaBaseCompetencia)">
                <td>
                    <div>
                        @item.areaCurricular
                    </div>
                </td>
                <td>
                    <div>
                        @item.competencia
                    </div>
                </td>
                <td>
                    <div>
                        @item.capacidad
                    </div>
                </td>
                <td>
                    <div class="eliminarCompetenciaCapacidadArea">
                        <img src="~/Content/Images/eliminar.png" alt="Competencia Capacidad Area" />
                    </div>
                </td>
            </tr>
        }

    </tbody>

</table>

<script type="text/javascript">

    $(".eliminarCompetenciaCapacidadArea").on("click", function () {
        var objeto = $(this);
        var id = $(this).parents(".filaCompetenciaxArea").attr("pidcurriculabasecompetencia");
        $.post('@Url.Action("ElininarCompetenciaxArea", "Curricula")', { idCurriculaBaseCompetencia: id }, function (data) {
            var obj = jQuery.parseJSON(data);
            if (obj) {
                objeto.parents(".filaCompetenciaxArea").hide("slow");
            } else {
                alert('Se presentaron incoveniente al eliminar el registro');
            }
        ssss});
    });

</script>

Colegio/Innova/Views/Curricula/ListaBase.cshtml
@{

    var lista = ViewBag.Lista as List<Innova.Models.CurriculaBase>;
}

<button class="btn btn-primary" type="submit" id="btnNuevaBase" style="align-content:flex-end">
    Nuevo
</button>



<table id="myTableAsesor" class="table table-bordered">

    <thead>
        <tr>
            <th>Codigo</th>
            <th>Año</th>
            <th>Resolución Ministerial</th>
            <th>Estado</th>
            <th></th>
            <th></th>
        </tr>
    </thead>

    <tbody>


        @{
            System.Diagnostics.Debug.Assert(lista != null, "lista != null");
        }
        @foreach (var item in lista)
        {
            <tr class="filaBase" pidbase="@(item.IdCurriculaBase)">
                <td>
                    <div>
                        @item.IdCurriculaBase
                    </div>
                </td>
                <td>
                    <div>
                        @item.Año
                    </div>
                </td>
                <td>
                    <div>
                        @item.NumeroResolucion
                    </div>
                </td>
                <td>
                    <div>
                        @if (Convert.ToBoolean(item.Vigencia))
                        {
                            <label>Vigente</label>
                        }
                        else
                        {
                            <label>No Vigente</label>
                        }
                    </div>
                </td>
                <td>
                    <div class="EditarBase">
                        <img src="~/Content/Images/editar.png" alt="Detalles de Curricula Base" />
                    </div>
                </td>
                <td>
                    <div class="AddCompetenciaCapacidadArea">
                        <img src="~/Content/Images/detalles.png" alt="Competencia Capacidad Area" />
                    </div>
                </td>
            </tr>
        }

    </tbody>

</table>

<!-- Modal Curricula Base-->
<div class="modal fade" id="BasePopup" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">

                <div class="col-md-12">
                    <div class="col-md-12 label label-default">
                        <div class="col-md-6" style="text-align: left">
                            <h5>Registrar Curricula Base</h5>
                        </div>
                        <div class="col-md-6" style="text-align: right">
                            <button type="button" data-dismiss="modal" aria-label="Close" class="btn btn-default">CERRAR</button>
                        </div>
                    </div>
                </div>

            </div>
            <div class="modal-body" id="modal-body">
                ...
            </div>
        </div>
    </div>
</div>

<!-- Modal Competencia Capacidad Area-->
<div class="modal fade modal-lg" id="CompetenciaCapacidadAreaPopup" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content modal-lg">
            <div class="modal-header">

                <div class="col-md-12">
                    <div class="col-md-12 label label-default">
                        <div class="col-md-6" style="text-align: left">
                            <h5>Competencias y capacidades por área curricular</h5>
                        </div>
                        <div class="col-md-6" style="text-align: right">
                            <button type="button" data-dismiss="modal" aria-label="Close" class="btn btn-default">CERRAR</button>
                        </div>
                    </div>
                </div>

            </div>
            <div class="modal-body modal-lg" id="modal-body">
                ...
            </div>
        </div>
    </div>
</div>


<script type="text/javascript">

    $("#btnNuevaBase").on("click", function () {
        $.post('@Url.Action("FormBase", "Curricula")', function (data) {
            if (data != null) {
                $('#BasePopup').find('.modal-body').html(data);
                $('#BasePopup').modal('show');
            }
        });
    });

    $(".EditarBase").on("click", function () {
        var id = $(this).parents(".filaBase").attr("pidbase");
        $.post('@Url.Action("FormBase", "Curricula")', { idCurriculaBase: id }, function (data) {
            if (data != null) {
                $('#BasePopup').find('.modal-body').html(data);
                $('#BasePopup').modal('show');
            }
        });
    });

    $(".AddCompetenciaCapacidadArea").on("click", function () {
        var id = $(this).parents(".filaBase").attr("pidbase");
        $.post('@Url.Action("FormCompetenciaCapacidadArea", "Curricula")', { idCurriculaBase: id }, function (data) {
            if (data != null) {
                $('#CompetenciaCapacidadAreaPopup').find('.modal-body').html(data);
                $('#CompetenciaCapacidadAreaPopup').modal('show');
            }
        });
    });



    @*$(".EliminarEvento").on("click", function () {
        var objeto = $(this);
        var id = $(this).parents(".filaEvento").attr("pidEvento");

        if (confirm("¿Seguro de eliminar el registro?")) {

            $.post('@Url.Action("EliminarEvento", "Inicio")', { idEvento: id }, function (data) {
                var obj = jQuery.parseJSON(data);
                if (obj) {
                    objeto.parents(".filaEvento").hide("slow");
                } else {
                    alert("Hubo un incoveniente al eliminar el registro");
                }
            });
        }
        return false;
    });*@


</script>